server:
  port: ${PORT:9900}

spring:
  profiles:
    active: local
  application:
    name: loeyae-service-center
  security:
    basic:
      enable: true #开启基于HTTP basic的认证
    user: #配置用户的账号信息
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PWD:ad2020min}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}
    appname: ${spring.application.name}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: 注册中心(${spring.cloud.client.ip-address}:${server.port})
  server:
    enable-self-preservation: ${SELF_PRESERVATION:false}
    responseCacheUpdateInvervalMs: 3000
    responseCacheAutoExpirationInSeconds: 180
    eviction-interval-timer-in-ms: 3000
  client:
    registerWithEureka: ${BOOL_REGISTER:true}
    fetchRegistry: ${BOOL_FETCH:true}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/}

##开启所有端点
management:
  endpoint:
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
    resume:
      enabled: true
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'