server:
  port: ${PORT:9902}

spring:
  profiles:
    active: local
  application:
    name: loeyae-zipkin-server
management:
  metrics:
    web:
      server:
        auto-time-requests: false

logging:
  level:
    org.springframework.web.reactive: WARN