eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:ad2020min}@${EUREKA_SERVICE_HOST:loeyae-service-center-0.loeyae-service-center}:${EUREKA_SERVICE_PORT:9900}/eureka/}
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

    hostname: ${ZIPKIN_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
    instance-id: Zipkin(${spring.cloud.client.ip-address}:${server.port})
