server:
  port: ${PORT:9904}

spring:
  profiles:
    active: local
  application:
    name: loeyae-demo
  messages:
    basename: classpath:i18n/messages
    encoding: UTF-8
  flyway:
    enabled: true
    encoding: utf-8
    clean-disabled: true

# Mybatis-Plus Config
mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  # 枚举类扫描
  typeEnumsPackage: com.loeyae.cloud.*.enums
logging:

  level:
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO