server:
  port: ${PORT:9901}

spring:
  profiles:
    active: local
  application:
    name: loeyae-gateway
  redis:
    host: ${REDIS_HOST:redis.dev.loeyae.com}
    port: ${REDIS_PORT:3179}
    password: ${REDIS_PASS:zBNLNoZZ5Hapmf61vtBHHgXd7woBaWR4}
    database: ${REDIS_DB:1}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          predicates:
            - name: Path
              args:
                pattern: "'/v1/'+serviceId+'/**'"
          filters:
            - name: RewritePath
              args:
                regexp: "'/v1/'+serviceId+'/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
      routes:
        - id: upload-file
          uri: http://192.168.163.93:8888
          predicates:
            - Path=/upload/**
          filters:
            - StripPrefix=1
        - id: loeyae-demo
          uri: lb://loeyae-demo
          predicates:
            - Path=/api/demo/**
          filters:
            - StripPrefix=1
        - id: order-food
          uri: lb://api-server
          predicates:
            - Path=/api/**
        - id: order-food-callback
          uri: lb://api-server
          predicates:
            - Path=/callback/**
        - id: file-server
          uri: lb://loeyae-files-server
          predicates:
            - Path=/file/**
        - id: demo
          uri: lb://dotnet-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

ribbon:
  # 请求连接的超时
  ConnectTimeout: 1000
  # 请求处理的超时时间
  ReadTimeout: 10000
  MaxAutoRetriesNextServer: 0

feign:
  httpclient:
    enabled: false
  hystrix:
    enabled: true
  ###开启压缩
  client:
    config:
      #服务名，填写default为所有服务
      default:
        # 连接时间
        connectTimeout: 6000
        # 超时时间
        readTimeout: 6000
        loggerLevel: basic
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      ###配置压缩文档类型及最小压缩的文档大小
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

# 熔断器设置 HystrixCommandProperties
hystrix:
  threadpool:
    default:
      # 并发执行的最大线程数，默认10
      coreSize: 1000
      maximumSize: 1000
      allowMaximumSizeToDivergeFromCoreSize: true
      # BlockingQueue的最大队列数
      maxQueueSize: 1000
      # 即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 1000
  command:
    default:
      # 是否开启通过请求缓存提供去重复数据功能。 默认为true
      requestCache:
        enabled: false
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            #设置超时熔断时间 15秒
            timeoutInMilliseconds: 30000
      # 短路限制数量
      circuitBreaker:
        requestVolumeThreshold: 1000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000

##开启所有端点
management:
  endpoint:
    pause:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
    resume:
      enabled: true
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

loeyae:
  verifyTokenUrls: ${VERIFY_TOKEN_URLS:/api/**, /file/**, /demo/**, /v1/**}
  skipTokenUrls: ${SKIP_TOKEN_URLS:/api/oauth/**, /api/YeepayMng/GetOpenId, /open/api/**, /**/get/token, /**/group1/M00/**/*}
  skipExcludeUrls: ${SKIP_EXCLUDE_URLS:/api/oauth/profile, }
  jwtSecretKey: ${JWT_SECRET_KEY:123asd456qwe789zxc}
  isAdminKey: ${IS_ADMIN_KEY:isAdmin}
  identifiedId: ${IDENTIFIED_ID:userId}
  applicationKey: ${APPLICATION_KEY:appId}
  permissionEnabled: false
  permissionCachedEnabled: false
  permissionCachePrefix: "ly:gw:pf_"
  permissionCacheExpire: 7200
  permissionRouted: false
  permissionMethodMatch: false


logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.cloud.gateway.handler: INFO
    org.springframework.cloud.gateway.filter: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO

