eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:ad2020min}@${EUREKA_SERVICE_HOST:loeyae-service-center-0.loeyae-service-center}:${EUREKA_SERVICE_PORT:9900}/eureka/}
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

    hostname: ${GATEWAY_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
    instance-id: 网关(${spring.cloud.client.ip-address}:${server.port})

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: upload-file
          uri: http://172.24.99.88:8888
          predicates:
            - Path=/upload/**
          filters:
            - StripPrefix=1
        - id: order-food
          uri: lb://api-server
          predicates:
            - Path=/api/**
            - Path=/callback/**
        - id: file-server
          uri: lb://loeyae-files-server
          predicates:
            - Path=/file/**
        - id: front-end
          uri: http://order-food-web.hq-app:80
          predicates:
            - Path=/**