debug: false
spring:
  redis:
    host: ${REDIS_HOST:redis.dev.loeyae.com}
    port: ${REDIS_PORT:3179}
    password: ${REDIS_PASS:zBNLNoZZ5Hapmf61vtBHHgXd7woBaWR4}
    database: ${REDIS_DB:2}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:ad2020min}@${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:9900}/eureka/
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    ip-address: 127.0.0.1
    prefer-ip-address: true
    hostname: ${GATEWAY_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
    instance-id: 网关(${spring.cloud.client.ip-address}:${server.port})

logging:
  level:
    org.springframework.cloud.gateway: WARN
loeyae:
  jwtSecretKey: abc123def456ghi789jkl0
  permissionEnabled: true
  permissionCachedEnabled: true
service:
  oauth:
    name: loeyae-demo
    url:
    api:
      menu: "/demo/test/menu/"
      permission: "/demo/test/permission/"