debug: false
spring:
  application:
    name: loeyae-message-local
  rabbitmq:
    host: 119.4.240.179
    port: 30337
    username: hqt
    password: Mq123@hqt

# eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:ad2020min}@${EUREKA_SERVICE_HOST:localhost}:${EUREKA_SERVICE_PORT:9900}/eureka/}
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己） 必须大于 lease-renewal-interval-in-seconds
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    hostname: ${INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
    instance-id: 消息服务(${spring.cloud.client.ip-address}:${server.port})
