---
apiVersion: v1
kind: Service
metadata:
  name: loeyae-message-server
  namespace: devops
spec:
  ports:
    - port: 80                                    #
      targetPort: 9905
      name: web
  # clusterIP: None
#  type: NodePort
  selector:
    app: loeyae-message-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loeyae-message-server
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loeyae-message-server
  template:
    metadata:
      labels:
        app: loeyae-message-server
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: loeyae-message-server
          image: hub.bys.cd:30339/library/loeyae_message_server:{TAG}
          imagePullPolicy: Always
          args:
            - --spring.profiles.active={ENV}
          ports:
            - containerPort: 9905
              name: web
          resources:
            limits:
              # jvm会自动发现该限制
              memory: 512Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -XX:MaxRAMFraction=2
                -XX:CICompilerCount=8
                -XX:ActiveProcessorCount=8
                -XX:+UseG1GC
                -XX:+AggressiveOpts
                -XX:+UseFastAccessorMethods
                -XX:+UseStringDeduplication
                -XX:+UseCompressedOops
                -XX:+OptimizeStringConcat
            - name: EUREKA_USER
              value: admin
            - name: EUREKA_PWD
              value: ad2020min
            - name: EUREKA_SERVER
              value: "http://${EUREKA_USER}:${EUREKA_PWD}@loeyae-service-center-0.loeyae-service-center.devops:9900/eureka/"
            - name: MESSAGE_SERVER_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.message-server