---
apiVersion: v1
kind: Service
metadata:
  name: loeyae-zipkin-server
  namespace: devops
spec:
  ports:
    - port: 80                                    #
      targetPort: 9902
      nodePort: 31909
      name: web
#   clusterIP: None
  type: NodePort
  selector:
    app: loeyae-zipkin-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loeyae-zipkin-server
  namespace: devops
spec:
  serviceName: loeyae-zipkin-server
  replicas: 1
  selector:
    matchLabels:
      app: loeyae-zipkin-server
  template:
    metadata:
      labels:
        app: loeyae-zipkin-server
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: loeyae-zipkin-server
          image: hub.dev.loeyae.com:30339/library/loeyae_zipkin_server:{TAG}
          imagePullPolicy: Always
          args:
            - --spring.profiles.active={ENV}
          ports:
            - containerPort: 9902
              hostPort: 9902
              name: web
          resources:
            limits:
              # jvm会自动发现该限制
              memory: 512Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -XX:MaxRAMFraction=2
                -XX:CICompilerCount=8
                -XX:ActiveProcessorCount=8
                -XX:+UseG1GC
                -XX:+AggressiveOpts
                -XX:+UseFastAccessorMethods
                -XX:+UseStringDeduplication
                -XX:+UseCompressedOops
                -XX:+OptimizeStringConcat
            - name: STORAGE_TYPE
              value: mysql
            - name: MYSQL_USER
              value: {MYSQL_USER}
            - name: MYSQL_PASS
              value: "{MYSQL_PASS}"
            - name: MYSQL_HOST
              value: "{MYSQL_HOST}"
            - name: MYSQL_TCP_PORT
              value: "{MYSQL_PORT}"
            - name: EUREKA_USER
              value: admin
            - name: EUREKA_PWD
              value: ad2020min
            - name: EUREKA_SERVER
              value: "http://${EUREKA_USER}:${EUREKA_PWD}@loeyae-service-center-0.loeyae-service-center.devops:9900/eureka/"
            - name: ZIPKIN_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.zipkin
  podManagementPolicy: "Parallel"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: loeyae-zipkin-server
  namespace: devops
spec:
  rules:
    - host: zipkin.dev.loeyae.com
      http:
        paths:
          - path: /
            backend:
              serviceName: loeyae-zipkin-server
              servicePort: web
  tls:
    - secretName: dev.loeyae-certs
