---
apiVersion: v1
kind: Service
metadata:
  name: loeyae-service-center
  labels:
    app: loeyae-service-center
spec:
  ports:
    - port: 9900                                    #
      targetPort: 9007
      nodePort: 31907
      name: loeyae-service-center
  # clusterIP: None
  type: NodePort
  selector:
    app: loeyae-service-center
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loeyae-service-center
spec:
  serviceName: loeyae-service-center
  replicas: 3
  selector:
    matchLabels:
      app: loeyae-service-center
  template:
    metadata:
      labels:
        app: loeyae-service-center
    spec:
      containers:
        - name: loeyae-service-center
          image: hub.byc.cd/library/loeyae_service_center:{TAG}
          ports:
            - containerPort: 9007
          resources:
            limits:
              # jvm会自动发现该限制
              memory: 512Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -XX:MaxRAMFraction=2
                -XX:CICompilerCount=8
                -XX:ActiveProcessorCount=8
                -XX:+UseG1GC
                -XX:+AggressiveOpts
                -XX:+UseFastAccessorMethods
                -XX:+UseStringDeduplication
                -XX:+UseCompressedOops
                -XX:+OptimizeStringConcat
            - name: EUREKA_SERVER
              value: "http://loeyae-service-center-0.loeyae-service-center:9007/eureka/,http://loeyae-service-center-1.loeyae-service-center:9007/eureka/,http://loeyae-service-center-2.loeyae-service-center:9007/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.eureka
  podManagementPolicy: "Parallel"