---
apiVersion: v1
kind: Service
metadata:
  name: loeyae-service-center
  namespace: hq-app
spec:
  ports:
    - port: 80                                    #
      targetPort: 9900
      name: web
  # clusterIP: None
#  type: NodePort
  selector:
    app: loeyae-service-center

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loeyae-service-center
  namespace: hq-app
spec:
  serviceName: loeyae-service-center
  replicas: 2
  selector:
    matchLabels:
      app: loeyae-service-center
  template:
    metadata:
      labels:
        app: loeyae-service-center
    spec:
      containers:
        - name: loeyae-service-center
          image: loeyae_service_center:{TAG}
          imagePullPolicy: Always
          args:
            - --spring.profiles.active={ENV}
          ports:
            - containerPort: 9900
              hostPort: 9900
              name: web
          resources:
            limits:
              # jvm会自动发现该限制
              memory: 512Mi
          env:
            - name: SELF_PRESERVATION
              value: true
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -XX:MaxRAMFraction=2
                -XX:CICompilerCount=8
                -XX:ActiveProcessorCount=8
                -XX:+UseG1GC
                -XX:+AggressiveOpts
                -XX:+UseFastAccessorMethods
                -XX:+UseStringDeduplication
                -XX:+UseCompressedOops
                -XX:+OptimizeStringConcat
            - name: EUREKA_USER
              valueFrom:
                secretKeyRef:
                  name: eureka-secret
                  key: user
            - name: EUREKA_PWD
              valueFrom:
                secretKeyRef:
                  name: eureka-secret
                  key: password
            - name: EUREKA_SERVER
              value: "http://${EUREKA_USER}:${EUREKA_PWD}@loeyae-service-center-0.loeyae-service-center:9900/eureka/,http://${EUREKA_USER}:${EUREKA_PWD}@loeyae-service-center-1.loeyae-service-center:9900/eureka/,http://${EUREKA_USER}:${EUREKA_PWD}@loeyae-service-center-2.loeyae-service-center:9900/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.eureka
  podManagementPolicy: "Parallel"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: loeyae-service-center
  namespace: hq-app
spec:
  rules:
    - host: eureka.local
      http:
        paths:
          - path: /
            backend:
              serviceName: loeyae-service-center
              servicePort: web
  tls:
    - secretName: local-certs
