spring:
  # 链路追踪
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_HOST:loeyae-zipkin-server.hq-app}:${ZIPKIN_SERVICE_PORT:80}
  sleuth:
    sampler:
      #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:ad2020min}@${EUREKA_SERVICE_HOST:loeyae-service-center-0.loeyae-service-center}:${EUREKA_SERVICE_PORT:9900}/eureka/}
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

    hostname: ${FILES_SERVER_INSTANCE_HOSTNAME:${spring.cloud.client.ip-address}}
    instance-id: 文件服务(${spring.cloud.client.ip-address}:${server.port})

fdfs:
  so-timeout: 5000
  connect-timeout: 5000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - ${FASTDFS_SERVICE_HOST:172.24.99.88}:${FASTDFS_SERVICE_PORT:22122}
  web-server-url: ${FASTDFS_SERVICE_HOST:www.local}
